---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# 2020.2.0
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: f0b3942b49880400994f62c064afd4ef909539eb
  tag: 202.6397.94

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples
